### PR TITLE
Add jedi-direx:hide-imports option

### PR DESCRIPTION
**Pull request by immerrr**
This should provide enough customization to fix issue #10.

### CODE REVIEW

**Comment by tkf** [comment]
Filtering `(cdr (oref node :cache))` before passing it to `mapcar` is simpler, don't you think?

Something like this

``` cl
(defun jedi-direx:-filter-cache (items)
  ;; filter out anything you want
  )

(defmethod direx:node-children ((node jedi-direx:object))
  (mapcar 'jedi-direx:node-from-cache
          (jedi-direx:-filter-cache (cdr (oref node :cache)))))
```

**Comment by immerrr** [comment]
Ok, that makes sense. I was trying to reuse `type` binding that was already available in `node-from-cache` function, but I agree that is hackish.

**Comment by tkf** [comment]
If we have performance problem then reusing binding is a way to go. But until then I just want readability.

I think using `cl-loop` is a bit better than `delq`+`mapcar` but since explaining it is harder than (as hard as?) writing it I will just merge it.

Thanks for the patch anyway!

**Comment by immerrr** [comment]
`cl-loop` will also require `cl-lib`. And I keep forgetting syntax of its clauses :) If adding requirements is OK, I'd suggest dash.

**Comment by tkf** [comment]
Most of its dependencies requires cl-lib so cl-lib is already an implicit dependency. So I guess stick with cl-lib.  Dash is fine but cl is also as cool as it and covers areas other than loop stuff.  I know people don't like cl but cl's history is just too... unfortunate :)

**Comment by wyuenho** [comment]
Hmmm, I have hide imports set to t and the imports are still showing. Doesn't seem to work?

**Comment by dpkatz** [comment]
Same here.  My take is that the problem is on line 75 in `jedi-direx:-filter-cache`:

```
(let ((item-type (plist-get (car item) :item-type)))
```

When I look at the structure of an `item`, I find that the type field is named `:type`, not `:item-type`.  If I change that line to read 

```
(let ((item-type (plist-get (car item) :type)))
```

then it works fine.

**Pull request merged**
